### ISSUE TITLE
返回类的泛型如果是推断"?"，则运行文档时报错

### ISSUE THREAD

**Issue by Machaing** [YeDaxia/JApiDocs#106]
`
@RestController
@RequestMapping("/test")
public class TestController {

	@GetMapping("1")
	public APIResult<?> test1Controller() {
		return APIResult.success("hello world");
	}

	@GetMapping("2")
	public APIResult<?> test2Controller() {
		TestUserResp testUserResp = new TestUserResp();
		testUserResp.setId("1");
		testUserResp.setUserName("mzy");
		testUserResp.setAge(11);

		return APIResult.success(testUserResp);
	}

	public static void main(String[] args) {
		DocsConfig config = new DocsConfig();
		config.setProjectPath("E:\\Project\\demo\\3.5 SpringController-Jdoc");
		config.setProjectName("demo"); // project name
		config.setApiVersion("V1.0");       // api version
		config.setDocsPath("E:\\Project\\demo\\3.5 SpringController-Jdoc\\api-doc");
		config.setAutoGenerate(Boolean.TRUE);
		Docs.buildHtmlDocs(config);
	}
}

@Data
@Builder
public class APIResult<T> {
	private String msg;
	private String code;
	private T data;

	private static String COMMON_SUCCESS_CODE = "1";

	static public  <T> APIResult<T> success(T data) {
		return new APIResult<>(null, COMMON_SUCCESS_CODE, data);
	}
}
`

报错信息：
`Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.WildcardType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
	at io.github.yedaxia.apidocs.ParseUtils.parseFieldNode(ParseUtils.java:478)
	at io.github.yedaxia.apidocs.ParseUtils.lambda$innerParseClassNode$10(ParseUtils.java:359)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.ParseUtils.lambda$innerParseClassNode$11(ParseUtils.java:323)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.ParseUtils.lambda$innerParseClassNode$12(ParseUtils.java:303)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.ParseUtils.innerParseClassNode(ParseUtils.java:264)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNode(ParseUtils.java:257)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:240)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseClassNodeByType(AbsControllerParser.java:257)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.handleResponseNode(AbsControllerParser.java:244)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.handleResponseNode(SpringControllerParser.java:199)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:206)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:28)
	at com.example.demo.controller.TestController.main(TestController.java:44)`

通过断点代码分析是 ParseUtils.java 的 parseFieldNode 方法在解析返回泛型类(APIResult)的泛型的字段，如果类泛型推断为?，无法给其类的泛型字段初始化其类型。

如果要解决该问题，我认为要解析Controller代码的返回语句(return ....)来获得？是什么类型。反射API貌似是可以做到。

**Comment by Machaing** [comment]
请问这个仓库有没有定义pr规范？我想提一个pr，我是直接fork后在master分支改然后提交pr。还是要开一个分支？

**Comment by lan149** [comment]
统一返回APIResult<?>这个，是不是太粗暴了？我们只有响应体里面不需要data内容的时候才允许在泛形里面填写“?”，这个我确认可以正常生成Docs。我们编码规范里面是要求大家，有正常响应体data的时候，一定要在泛形里面标注清楚响应体data的对象。
就比如说你上面的第一个方法我们编码规范里面会要求写成：APIResult<String>；第二个方法我们编码规范里面会要求写成：APIResult<TestUserResp>

**Comment by Machaing** [comment]
> 统一返回APIResult<?>这个，是不是太粗暴了？我们只有响应体里面不需要data内容的时候才允许在泛形里面填写“?”，这个我确认可以正常生成Docs。我们编码规范里面是要求大家，有正常响应体data的时候，一定要在泛形里面标注清楚响应体data的对象。
> `就比如说你上面的第一个方法我们编码规范里面会要求写成：APIResult<String>；第二个方法我们编码规范里面会要求写成：APIResult<TestUserResp>`

没错，很多公司或者项目的规范甚至不会用泛型，只用一个Object 来声明data。如果是泛型也会像你描述的那样声明data的具体类型。

但从语法角度开率，jdk8允许我使用推断声明（？)，如果不支持解析推断类型，我建议要排除自身封装的异常信息告诉用户。
