### ISSUE TITLE
Caused by: java.lang.ClassCastException: com.github.javaparser.ast.type.VoidType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType 	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:215) 	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$null$9(AbsControllerParser.java:126) 	at java.util.Optional.ifPresent(Optional.java:159) void方法有问题？

### ISSUE THREAD

**Issue by qq419464926** [YeDaxia/JApiDocs#17]

**Comment by YeDaxia** [comment]
你好，方便加一个Q群吗？我想详情了解一下bug出现的情景～

**Comment by qq419464926** [comment]
申请加群了
