### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by yaodwwy** [YeDaxia/JApiDocs#27]
windows env.  projectPath = C:\\dev\\JApiDocs\\springDemo
Error Message:

at io.github.yedaxia.apidocs.Utils.streamToString(Utils.java:86)
        at io.github.yedaxia.apidocs.doc.HtmlControllerDocBuilder.getControllerTpl(HtmlControllerDocBuilder.java:124)
        at io.github.yedaxia.apidocs.doc.HtmlControllerDocBuilder.buildDoc(HtmlControllerDocBuilder.java:27)
        at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateControllersDocs(AbsDocGenerator.java:47)
        at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateDocs(AbsDocGenerator.java:31)
        at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:32)
        at io.github.yedaxia.apidocs.Docs.main(Docs.java:23)

**Comment by YeDaxia** [comment]
try:

```
projectPath=C:/dev/JApiDocs/springDemo
```
or
```
projectPath=C:\\dev\\JApiDocs\\springDemo
```
