### ISSUE TITLE
接口返回值封装了 提示找不到java文件

### ISSUE THREAD

**Issue by GuoZG** [YeDaxia/JApiDocs#40]
`
Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file : D:\work-spance\rzy\hr-website\src\main\java\com\hr\web\controller\xxxx.java, className : ResponseData
	at io.github.yedaxia.apidocs.ParseUtils.searchJavaFile(ParseUtils.java:51)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:222)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$9(AbsControllerParser.java:153)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:88)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:40)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:37)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateControllersDocs(AbsDocGenerator.java:45)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateDocs(AbsDocGenerator.java:34)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:31)
	at com.hr.web.utils.ApiDocs.main(ApiDocs.java:15)
`

封装的类不在本工程 在父工程

**Comment by YeDaxia** [comment]
谢谢反馈，麻烦你提供以下项目的目录结构？

多模块项目项目目录应该指定根目录；另外你可以先试一下手动把源码目录(src)配置进去，可以添加多个：

```
DocsConfig => addJavaSrcPath
```

**Comment by GuoZG** [comment]
<modules>
        
        <module>../hr-common-core</module>
        
        <module>../hr-website</module>
</modules>

这是parent 的pom 返回值封装在 common 接口在 website

**Comment by Zephyr006** [comment]
Similer problem as below：
```
Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file : D:\Dong\code\bayss\bws-basic-edition\bws-server\src\main\java\com\bayss\bws\controller\AuthController.java, className : Map
	at io.github.yedaxia.apidocs.ParseUtils.searchJavaFile(ParseUtils.java:51)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:222)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.setRequestBody(SpringControllerParser.java:157)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$null$6(SpringControllerParser.java:113)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$afterHandleMethod$7(SpringControllerParser.java:106)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.afterHandleMethod(SpringControllerParser.java:101)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$9(AbsControllerParser.java:142)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:88)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:40)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:37)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateControllersDocs(AbsDocGenerator.java:45)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateDocs(AbsDocGenerator.java:34)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:31)
	at
```
Source code :
```java
// Method declaration
ResponseEntity<RestResult> login(@RequestBody Map<String, String> loginForm)
```

**Comment by YeDaxia** [comment]
@Zephyr006 JApiDocs is implemented by parsing Java source code.  Please refer the document section [Code Style Requirements](https://japidocs.agilestudio.cn/#/?id=code-style-requirements).

**Comment by YeDaxia** [comment]
@GuoZG JApiDocs 支持泛型解析，可以把无法解析的返回对象字段提供以下么？你可以参考一下这个[方法](https://github.com/YeDaxia/JApiDocs/blob/master/springDemo/src/main/java/controller/UserController.java)：

```java
 /**
     * 用户列表
     * @param listForm
     * @author yedaxia
     */
    @RequestMapping(path = "list", method = {RequestMethod.GET,  RequestMethod.POST}  )
    public ApiResult<PageResult<UserVO>> list(UserListForm listForm){
        return null;
    }
```

**Comment by hoshaoniurou** [comment]
<img width="919" alt="8A520247-A780-4361-A6C4-F4EE6C3D73AC" src="https://user-images.githubusercontent.com/38946931/84989883-ee455580-b176-11ea-9de9-2911aa5d7c75.png">
如果返回值是外部jar引入的就不能直接拼接 JavaFilePath，本地根本没有这个文件，去 new File(javaFilePath); 肯定是失败的

**Comment by cxwangxixi** [comment]
> 谢谢反馈，麻烦你提供以下项目的目录结构？
> 
> 多模块项目项目目录应该指定根目录；另外你可以先试一下手动把源码目录(src)配置进去，可以添加多个：
> 
> ```
> DocsConfig => addJavaSrcPath
> ```



> 谢谢反馈，麻烦你提供以下项目的目录结构？
> 
> 多模块项目项目目录应该指定根目录；另外你可以先试一下手动把源码目录(src)配置进去，可以添加多个：
> 
> ```
> DocsConfig => addJavaSrcPath
> ```
addJavaSrcPath就指定module，就又会出现找不到其他jar包里的类的情况，好像还是解决不了

**Comment by YeDaxia** [comment]
@hoshaoniurou JApiDocs 目前是不支持外部jar包的， 请参考文档的[编码规范](https://japidocs.agilestudio.cn/#/zh-cn/?id=%e7%bc%96%e7%a0%81%e8%a7%84%e8%8c%83)部分。
