### ISSUE TITLE
Cannot find java file

### ISSUE THREAD

**Issue by Gamehu** [YeDaxia/JApiDocs#48]
hello:

The error message is as follows：

信息: info: start to parse controller file : AlarmController.java
Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file : D:xxxx\src\main\java\com\riil\baymax\basewebplatform\web\controller\alarm\AlarmController.java, className : AlarmPage
	at io.github.yedaxia.apidocs.ParseUtils.searchJavaFile(ParseUtils.java:51)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:222)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$9(AbsControllerParser.java:153)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:88)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:40)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:37)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateControllersDocs(AbsDocGenerator.java:45)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateDocs(AbsDocGenerator.java:34)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:31)
	at com.riil.baymax.basewebplatform.web.ApiDocUtil.main(ApiDocUtil.java:28)

dir:
![image](https://user-images.githubusercontent.com/10043320/85246558-85fbba00-b47d-11ea-8459-c1bd26d9b83f.png)

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/85246587-9875f380-b47d-11ea-8247-c9f6ae73021c.png)

**Comment by YeDaxia** [comment]
Is AlarmPage in source or jar ?

**Comment by Gamehu** [comment]
> Is AlarmPage in source or jar ?

source.

in maven module

**Comment by YeDaxia** [comment]
please provide your apidoc.log, a file in docs path.

**Comment by Gamehu** [comment]
[apidoc.log](https://github.com/YeDaxia/JApiDocs/files/4812617/apidoc.log)

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/85278360-700aeb00-b4b7-11ea-942f-ca6759faef84.png)

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/85278415-8618ab80-b4b7-11ea-8a6b-c9e4d3b0b1b0.png)

**Comment by Gamehu** [comment]
DocsConfig config = new DocsConfig();
        // root project path
        config.setProjectPath("D:\\baymax_projects\\riil-base-web-platform");
        config.addJavaSrcPath("D:\\baymax_projects\\riil-base-web-platform\\riil-base-web-platform-service");
        config.addJavaSrcPath("D:\\baymax_projects\\riil-base-web-platform\\riil-base-web-platform-web");
        config.addJavaSrcPath("D:\\baymax_projects\\riil-base-web-platform\\riil-base-web-platform-repository");

        // project name
        config.setProjectName("base-web");
        // api version
        config.setApiVersion("V1.0");
        // api docs target path
        config.setDocsPath("D:\\baymax_projects\\api-doc");
        // auto generate
        config.setAutoGenerate(Boolean.TRUE);
        // execute to generate
        Docs.buildHtmlDocs(config);

**Comment by YeDaxia** [comment]
please provide AlarmController.java, include the imports and the method return class `AlarmPage `, you can remove then method body.

**Comment by Gamehu** [comment]
package com.riil.baymax.basewebplatform.web.controller.alarm;

import com.alibaba.dubbo.config.annotation.Reference;
import com.riil.baymax.basewebplatform.service.bean.alarm.Alarm;
import com.riil.baymax.basewebplatform.service.bean.alarm.AlarmPage;
import com.riil.baymax.basewebplatform.service.bean.alarm.AlarmPageVO;
import com.riil.baymax.basewebplatform.service.bean.alarm.AreaComparison;
import com.riil.baymax.basewebplatform.service.bean.alarm.ProbeStrategy;
import com.riil.baymax.basewebplatform.service.bean.alarm.UpdateLog;
import com.riil.baymax.basewebplatform.service.bean.alarm.UrlLog;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

import static com.riil.baymax.basewebplatform.service.error.BaseWebErrorCode.BoardConstant.APP_LIST_CODE;
import static com.riil.baymax.basewebplatform.service.error.BaseWebErrorMsg.BoardConstant.APP_LIST_ERROR_MSG;

/**
 *  xxx
 * @author xxx
 */
@RestController
@RequestMapping(value = "/api/v1/event", produces = MediaType.APPLICATION_JSON_UTF8_VALUE, consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
public class AlarmController {
    @Reference(timeout = 60000, check = false)
    private IAlarmService alarmRpcService;

    @Autowired
    private ApplicationService applicationService;

    @Autowired
    private AlarmService alarmService;
    @Autowired
    private AlarmMatrixService alarmMatrixService;
    @Autowired
    private AlarmLogService alarmLogService;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    /**
     * xxxx
     *
     * @param vo
     * @return
     */
    @PostMapping(value = "/getAlarmPage")
    public AlarmPage<Alarm> getAlarmPage(@RequestBody AlarmPageVO vo) {
        AlarmListQuery query = new AlarmListQuery();
        query.setKeyword(vo.getKeyword());
        query.setAlarmLevel(vo.getLevelCode().getLevel());
        query.setPageNum(vo.getOffset() / vo.getPageSize() + 1);
        query.setPageSize(vo.getPageSize());
        query.setStartTime(vo.getStartTime());
        query.setEndTime(vo.getEndTime());
        query.setStatus(AlarmStatus.valueOf(vo.getAlarmStatus().name()));
        query.setRuleId(vo.getAlarmRule());
        CMSContext cmsContext = Context.getCmsContext();
        query.setUserId(cmsContext.getUserId());
        return alarmService.getAlarmPage(query);
    }

 

}

**Comment by YeDaxia** [comment]
It looks normal, maybe you should add my [wechat](https://weixin.qq.com/) to help solve this problem. 

my wechat id: DarcyYe

**Comment by Gamehu** [comment]
OK，Thanks！

**Comment by YeDaxia** [comment]
1.4.1 support read jar use reflection
