### ISSUE TITLE
自定义枚举类型参数异常

### ISSUE THREAD

**Issue by gjf450005950** [YeDaxia/JApiDocs#73]
```
信息: info: start to parse controller file : CommonController.java
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.VoidType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.handleResponseNode(AbsControllerParser.java:224)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.handleResponseNode(SpringControllerParser.java:183)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:192)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:28)
	at com.hp.it.css.mps.APIDocMain.main(APIDocMain.java:22)
```

方法：
```
  /**
   * 获取验证码图片
   * @param use 用途,下单:CREATE_ORDER、保修:CREATE_ISSUE
   * @param width 宽,默认200
   * @param height 高,默认50
   * @throws IOException
   */
  @GetMapping("/captcha")
  public void getCaptcha(
      @RequestParam(required = true) CaptchaUseEnum use,
      @RequestParam(defaultValue = "200") Integer width,
      @RequestParam(defaultValue = "50") Integer height,
      HttpServletRequest request,
      HttpServletResponse response)
      throws IOException {
    response.setHeader("Cache-Control", "no-store");
    response.setHeader("Pragma", "no-cache");
    response.setDateHeader("Expires", 0);
    response.setContentType("image/jpeg");
    LineCaptcha captcha = CaptchaUtil.createLineCaptcha(width, height);
    captcha.write(response.getOutputStream());
    request.getSession().setAttribute(use.getCode(), captcha.getCode());
    IoUtil.close(response.getOutputStream());
  }
```

```
/** 验证码用途 */
@Getter
public enum CaptchaUseEnum implements BaseEnum {
  ORDER("CREATE_ORDER"), // 下单
  ISSUE("CREATE_ISSUE"); // 保修

  private String code; // 用途(下单:CREATE_ORDER、Issue:CREATE_ISSUE)

  CaptchaUseEnum(String code) {
    this.code = code;
  }
}

/**
 * 通用枚举接口
 */
public interface BaseEnum {
    /**
     * 获取枚举编码
     *
     * @return 编码
     */
    String getCode();
}
```

**Comment by YeDaxia** [comment]
1.4.3 对枚举类型参数进行了支持
