### ISSUE TITLE
NullPointerException 甚么情况

### ISSUE THREAD

**Issue by renshuaiya** [YeDaxia/JApiDocs#77]
信息: info: start to parse controller file : ZtFlowController.java
java.lang.NullPointerException
	at io.github.yedaxia.apidocs.parser.ClassNode.getFieldDesc(ClassNode.java:180)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApiMap(ClassNode.java:167)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApi(ClassNode.java:135)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.setRequestBody(SpringControllerParser.java:192)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$afterHandleMethod$6(SpringControllerParser.java:123)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser$$Lambda$311/1561668.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$afterHandleMethod$7(SpringControllerParser.java:109)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser$$Lambda$304/13500464.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.afterHandleMethod(SpringControllerParser.java:104)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:181)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser$$Lambda$298/7905343.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser$$Lambda$276/25959901.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:28)

**Comment by YeDaxia** [comment]
可以通过关闭自动生成: `config.setAutoGenerate(Boolean.FALSE);` 然后通过`@ApiDoc`来排查出现问题的接口方法，从错误看，是解析传入参数造成的。

**Comment by windmzx** [comment]
```
    public List<Driver> filetoDriver(@ApiParam(value = "file", required = true) @RequestParam(value = "file") MultipartFile file) throws CommonException {
        if (file.isEmpty()) {
            throw new CommonException("文件异常");
        }
        File file1 = new File("driverfile" + System.currentTimeMillis());
        List<Driver> drivers1 = null;
        try {
            FileUtils.copyInputStreamToFile(file.getInputStream(), file1);

            List<Driver> drivers = EasyExcel.read(file.getInputStream()).head(Driver.class).sheet().doReadSync();
            for (int i = 0; i < drivers.size(); i++) {
                drivers.get(i).setUuid(UUID.randomUUID().toString());
                drivers.get(i).setRegistryDate(new Date(System.currentTimeMillis()));
            }

            drivers1 = driverService.insertDrivers(drivers);
            return drivers1;
        } catch (IOException e) {
            throw new CommonException("文件错误");
        }
```
可以定位到错误 不知道为什么会报错？

**Comment by YeDaxia** [comment]
1.4.2 List 类似解析的bug，1.4.3已经修复。
