### ISSUE TITLE
生成文档时报转换异常阻塞生成

### ISSUE THREAD

**Issue by ferren-qf** [YeDaxia/JApiDocs#87]
## 版本
1.4.2

## 异常说明
生成文档时报如下错误信息, void 不能进行转换
```
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.VoidType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.handleResponseNode(AbsControllerParser.java:224)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.handleResponseNode(SpringControllerParser.java:183)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:192)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:28)
	at cn.com.countrygarden.bi.main.test.other.TestJApiDocs.main(TestJApiDocs.java:14)
```
### 报错位置
io.github.yedaxia.apidocs.parser.AbsControllerParser#handleResponseNode

### 调试情况
![image](https://user-images.githubusercontent.com/24836644/89938073-8f68fd80-dc48-11ea-9961-011190c043d3.png)

**Comment by ferren-qf** [comment]
已有答复 #80
