### ISSUE TITLE
生成API文档空指针

### ISSUE THREAD

**Issue by liuboflyon145** [YeDaxia/JApiDocs#89]
Exception in thread "main" java.lang.NullPointerException
	at io.github.yedaxia.apidocs.parser.ClassNode.getFieldDesc(ClassNode.java:180)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApiMap(ClassNode.java:158)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApi(ClassNode.java:135)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.setRequestBody(SpringControllerParser.java:192)

**Comment by YeDaxia** [comment]
该issue无法提供错误发生的原因~ 暂时关闭。
