### ISSUE TITLE
解析jar包bean抛NullPointerException

### ISSUE THREAD

**Issue by liuxiuhao** [YeDaxia/JApiDocs#96]
Exception in thread "main" java.lang.NullPointerException
	at io.github.yedaxia.apidocs.parser.ClassNode.getFieldDesc(ClassNode.java:183)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApiMap(ClassNode.java:170)
	at io.github.yedaxia.apidocs.parser.ClassNode.toJsonApi(ClassNode.java:138)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.setRequestBody(SpringControllerParser.java:209)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$afterHandleMethod$6(SpringControllerParser.java:140)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.lambda$afterHandleMethod$7(SpringControllerParser.java:126)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at io.github.yedaxia.apidocs.parser.SpringControllerParser.afterHandleMethod(SpringControllerParser.java:121)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:190)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:28)
	at com.april.oms.web.tools.JapiDocsTool.main(JapiDocsTool.java:25)

----------------
io.github.yedaxia.apidocs.parser.FieldNode#notNull 是做什么用的，这里为null了
![image](https://user-images.githubusercontent.com/11626185/91789231-cd9e7f00-ec40-11ea-942d-04f00a4a05ef.png)

**Comment by nquanhao001** [comment]
什么时候发布新版本修复？ 等着用呢?

**Comment by YeDaxia** [comment]
> 什么时候发布新版本修复？ 等着用呢?

新版本没那么快发呢，这个问题已经修了提交了。你可以先自己编译一个版本~
